<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \Entities\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setAbout($about)
    {
        $this->__load();
        return parent::setAbout($about);
    }

    public function getAbout()
    {
        $this->__load();
        return parent::getAbout();
    }

    public function setActive($active)
    {
        $this->__load();
        return parent::setActive($active);
    }

    public function getActive()
    {
        $this->__load();
        return parent::getActive();
    }

    public function setCreated($created)
    {
        $this->__load();
        return parent::setCreated($created);
    }

    public function getCreated()
    {
        $this->__load();
        return parent::getCreated();
    }

    public function setModified($modified)
    {
        $this->__load();
        return parent::setModified($modified);
    }

    public function getModified()
    {
        $this->__load();
        return parent::getModified();
    }

    public function setDeleted($deleted)
    {
        $this->__load();
        return parent::setDeleted($deleted);
    }

    public function getDeleted()
    {
        $this->__load();
        return parent::getDeleted();
    }

    public function setCreateUser(\Entities\User $createUser = NULL)
    {
        $this->__load();
        return parent::setCreateUser($createUser);
    }

    public function getCreateUser()
    {
        $this->__load();
        return parent::getCreateUser();
    }

    public function setModifyUser(\Entities\User $modifyUser = NULL)
    {
        $this->__load();
        return parent::setModifyUser($modifyUser);
    }

    public function getModifyUser()
    {
        $this->__load();
        return parent::getModifyUser();
    }

    public function setDeleteUser(\Entities\User $deleteUser = NULL)
    {
        $this->__load();
        return parent::setDeleteUser($deleteUser);
    }

    public function getDeleteUser()
    {
        $this->__load();
        return parent::getDeleteUser();
    }

    public function addInstance(\Entities\Instance $instances)
    {
        $this->__load();
        return parent::addInstance($instances);
    }

    public function removeInstance(\Entities\Instance $instances)
    {
        $this->__load();
        return parent::removeInstance($instances);
    }

    public function getInstances()
    {
        $this->__load();
        return parent::getInstances();
    }

    public function addPost(\Entities\Post $posts)
    {
        $this->__load();
        return parent::addPost($posts);
    }

    public function removePost(\Entities\Post $posts)
    {
        $this->__load();
        return parent::removePost($posts);
    }

    public function getPosts()
    {
        $this->__load();
        return parent::getPosts();
    }

    public function addAttachment(\Entities\Attachment $attachments)
    {
        $this->__load();
        return parent::addAttachment($attachments);
    }

    public function removeAttachment(\Entities\Attachment $attachments)
    {
        $this->__load();
        return parent::removeAttachment($attachments);
    }

    public function getAttachments()
    {
        $this->__load();
        return parent::getAttachments();
    }

    public function addInteraction(\Entities\Interaction $interactions)
    {
        $this->__load();
        return parent::addInteraction($interactions);
    }

    public function removeInteraction(\Entities\Interaction $interactions)
    {
        $this->__load();
        return parent::removeInteraction($interactions);
    }

    public function getInteractions()
    {
        $this->__load();
        return parent::getInteractions();
    }

    public function addSecurity(\Entities\Security $security)
    {
        $this->__load();
        return parent::addSecurity($security);
    }

    public function removeSecurity(\Entities\Security $security)
    {
        $this->__load();
        return parent::removeSecurity($security);
    }

    public function getSecurity()
    {
        $this->__load();
        return parent::getSecurity();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'password', 'firstName', 'lastName', 'email', 'about', 'active', 'created', 'modified', 'deleted', 'createUser', 'modifyUser', 'deleteUser', 'instances', 'posts', 'attachments', 'interactions', 'security');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}