<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Instance
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Instance extends EntityRepository
{
}
