<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Interaction
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Interaction extends EntityRepository
{
}
