<?php

namespace Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * Security
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Security extends EntityRepository
{
}
